### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/contractor#20]
I'm struggling with writing a image resize contract for Files. One of the biggest issues is that I don't know how to debug my .contract scripts. 
Is there anyway to get the result / output of the Exec parameter?

**Comment by Philip-Scott** [comment]
You can pipe it's output using `>>` like any other command :)

**Comment by peteruithoven** [comment]
Very good point. I just experimented a bit. 

`/usr/local/bin/hello.sh` with:
```
#!/bin/bash
echo 'hello
```
Running that like `hello.sh >> /tmp/hello.sh.log` it creates that file with: `hello`. Perfect.

But `~/.local/share/contractor` with:
```
[Contractor Entry]
Name=Hello
MimeType=image
Exec=echo 'hello' >> /tmp/hello.log
```
or
```
[Contractor Entry]
Name=Hello
MimeType=image
Exec=hello.sh >> /tmp/hello.log
```
And running that on a file, no `/tmp/hello.log` is created. Am I doing this wrong?

Update, logging from the script executed by the contract does seem to work:
```
#!/bin/bash

exec 2> /tmp/hello.log
exec 1>&2

echo 'hello'
```

**Comment by peteruithoven** [comment]
I guess Exec is just limited and we'll need to forward the output inside the scripts we call with Exec (see update above)?

**Comment by peteruithoven** [comment]
If I understand the Desktop Entry Specification (which seems related), characters like > are reserved. 
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by Philip-Scott** [comment]
I'm that case, you can make it run a script and have the > in there :)
