### ISSUE TITLE
meson regression: contract directory no longer installed

### ISSUE THREAD

**Issue by decathorpe** [elementary/contractor#26]
The meson equivalent of `install (DIRECTORY DESTINATION ${CMAKE_INSTALL_FULL_DATAROOTDIR}/contractor)` is missing - so the contracts directory is no longer created upon installation.

**Comment by CameronNemo** [comment]
Can't this be handled by packaging? In Void an empty directory will be removed without some packaging hooks anyway.

**Comment by decathorpe** [comment]
@CameronNemo I *am* handling this in packaging now.

It's just best practice on fedora to have the main package own the directory structure it provides for its "children". In this case, contractor expects other packages to put their contracts in this directory, so contractor should create the directory and the contractor package should own it.

This has the nice benefit that - when removing contractor and all contracts - everything is cleaned up nicely, and no empty directories are left behind, cluttering the system.

**Comment by decathorpe** [comment]
Will this be reintroduced to meson, or will I have to keep doing this in packaging?

**Comment by decathorpe** [comment]
Alright, after discussing a similar issue in switchboard, we decided that it's probably easiest to deal with this in RPM packaging directly.
