### ISSUE TITLE
Is there a proper way to translate contract files?

### ISSUE THREAD

**Issue by NathanBnm** [elementary/contractor#35]
I'm currently working on the translation of an app  and I'm getting trouble translating the contract file. Is there a proper way to do it?

First I used to rename the file `rddn.contract.in` and use meson to rename it properly like we do for the desktop file. But when I try to generate the translation template using ninja it complains that the `.contract` file extension has not been recognized and it's content is not being added the template.

Then, I noticed that the file structure was the same than desktop fiiles so I found a parade by naming the file `rddn.contract.desktop.in` which seems to work becauses xgettext read the file the same way than a classic desktop file. But it's a bit tricky.

What do you think? Any help would be appreciated.

**Comment by NathanBnm** [comment]
Edit: Just noticed the app could not build by using this trick. So I currently don't have any solution

**Comment by jeremypw** [comment]
You do not need to translate contract files.  You can call Granite.Service.Contract.get_display_name () to get the internationalized name.

However, be aware that the contractor framework does not currently work with Flatpak applications and most of its usage is likely to be replaced by portals.

**Comment by jeremypw** [comment]
See for example https://github.com/codygarver/os-patch-file-roller-xenial/blob/master/data/file-roller-compress.contract.  You just need to provide the appropriate `Gettext-domain` key.

**Comment by jeremypw** [comment]
I guess this assumes that the string used for the `Name` key is the same as one used (and translated) in the associated app though.

**Comment by NathanBnm** [comment]
Thanks for the explanation @jeremypw

I'll report this to the developer 😄
